# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07kvstore\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"/\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"C\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x16\n\x0eleader_address\x18\x03 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x10ReplicateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\n\n\x02op\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x04 \x01(\t\"$\n\x11ReplicateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"\"\n\x0fSnapshotRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"r\n\x10SnapshotResponse\x12\x31\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32#.kvstore.SnapshotResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xaa\x01\n\tKVService\x12\x30\n\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x12\x30\n\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12\x39\n\x06\x44\x65lete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse2\xe1\x01\n\x0fInternalService\x12\x42\n\tReplicate\x12\x19.kvstore.ReplicateRequest\x1a\x1a.kvstore.ReplicateResponse\x12\x42\n\tHeartbeat\x12\x19.kvstore.HeartbeatRequest\x1a\x1a.kvstore.HeartbeatResponse\x12\x46\n\x0fRequestSnapshot\x12\x18.kvstore.SnapshotRequest\x1a\x19.kvstore.SnapshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPSHOTRESPONSE_DATAENTRY']._loaded_options = None
  _globals['_SNAPSHOTRESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_PUTREQUEST']._serialized_start=26
  _globals['_PUTREQUEST']._serialized_end=66
  _globals['_PUTRESPONSE']._serialized_start=68
  _globals['_PUTRESPONSE']._serialized_end=115
  _globals['_GETREQUEST']._serialized_start=117
  _globals['_GETREQUEST']._serialized_end=142
  _globals['_GETRESPONSE']._serialized_start=144
  _globals['_GETRESPONSE']._serialized_end=211
  _globals['_DELETEREQUEST']._serialized_start=213
  _globals['_DELETEREQUEST']._serialized_end=241
  _globals['_DELETERESPONSE']._serialized_start=243
  _globals['_DELETERESPONSE']._serialized_end=293
  _globals['_REPLICATEREQUEST']._serialized_start=295
  _globals['_REPLICATEREQUEST']._serialized_end=368
  _globals['_REPLICATERESPONSE']._serialized_start=370
  _globals['_REPLICATERESPONSE']._serialized_end=406
  _globals['_HEARTBEATREQUEST']._serialized_start=408
  _globals['_HEARTBEATREQUEST']._serialized_end=443
  _globals['_HEARTBEATRESPONSE']._serialized_start=445
  _globals['_HEARTBEATRESPONSE']._serialized_end=479
  _globals['_SNAPSHOTREQUEST']._serialized_start=481
  _globals['_SNAPSHOTREQUEST']._serialized_end=515
  _globals['_SNAPSHOTRESPONSE']._serialized_start=517
  _globals['_SNAPSHOTRESPONSE']._serialized_end=631
  _globals['_SNAPSHOTRESPONSE_DATAENTRY']._serialized_start=588
  _globals['_SNAPSHOTRESPONSE_DATAENTRY']._serialized_end=631
  _globals['_KVSERVICE']._serialized_start=634
  _globals['_KVSERVICE']._serialized_end=804
  _globals['_INTERNALSERVICE']._serialized_start=807
  _globals['_INTERNALSERVICE']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
